var searchData=
[
  ['rain_0',['Rain',['../classSupla_1_1Sensor_1_1Rain.html',1,'Supla::Sensor']]],
  ['rangeinput_1',['rangeInput',['../classSupla_1_1WebSender.html#ad0f64949fc01b2329dd4864dc918bef3',1,'Supla::WebSender::rangeInput(const char *key, const NumericInputSpec &amp;spec, const char *cssClass=nullptr)'],['../classSupla_1_1WebSender.html#a0012c343a31272a77f948614f352b3de',1,'Supla::WebSender::rangeInput(const char *name, const char *id, const NumericInputSpec &amp;spec, const char *cssClass=nullptr)']]],
  ['registeredcmdactionmap_2',['RegisteredCmdActionMap',['../structSupla_1_1Html_1_1RegisteredCmdActionMap.html',1,'Supla::Html']]],
  ['relay_3',['Relay',['../classRelay.html',1,'Relay'],['../classSupla_1_1Control_1_1Relay.html',1,'Supla::Control::Relay']]],
  ['relayhvacaggregator_4',['RelayHvacAggregator',['../classRelayHvacAggregator.html',1,'RelayHvacAggregator'],['../classSupla_1_1Control_1_1RelayHvacAggregator.html',1,'Supla::Control::RelayHvacAggregator']]],
  ['relayparameters_5',['RelayParameters',['../classRelayParameters.html',1,'RelayParameters'],['../classSupla_1_1Html_1_1RelayParameters.html',1,'Supla::Html::RelayParameters']]],
  ['remotedeviceconfig_6',['RemoteDeviceConfig',['../classRemoteDeviceConfig.html',1,'RemoteDeviceConfig'],['../classSupla_1_1Device_1_1RemoteDeviceConfig.html',1,'Supla::Device::RemoteDeviceConfig']]],
  ['remoteoutputinterface_7',['RemoteOutputInterface',['../classRemoteOutputInterface.html',1,'RemoteOutputInterface'],['../classSupla_1_1Control_1_1RemoteOutputInterface.html',1,'Supla::Control::RemoteOutputInterface'],['../classSupla_1_1Control_1_1RemoteOutputInterface.html#ae6dbfc3de7c7cf8a1d55e3ab78952155',1,'Supla::Control::RemoteOutputInterface::RemoteOutputInterface()'],['../classRemoteOutputInterface.html#ae6dbfc3de7c7cf8a1d55e3ab78952155',1,'RemoteOutputInterface::RemoteOutputInterface()']]],
  ['removesensor_8',['removeSensor',['../classSupla_1_1Control_1_1ValveBase.html#a1219856ed53ce43581a10a5853110fab',1,'Supla::Control::ValveBase::removeSensor()'],['../classValveBase.html#a1219856ed53ce43581a10a5853110fab',1,'ValveBase::removeSensor()']]],
  ['removesensordata_9',['removeSensorData',['../classSupla_1_1Sensor_1_1Container.html#ac97e08bfea047cd89d7af8ea2fe274fc',1,'Supla::Sensor::Container::removeSensorData()'],['../classContainer.html#ac97e08bfea047cd89d7af8ea2fe274fc',1,'Container::removeSensorData()']]],
  ['requestedstate_10',['RequestedState',['../structSupla_1_1Control_1_1LightingPwmBase_1_1RequestedState.html',1,'Supla::Control::LightingPwmBase']]],
  ['rgbbase_11',['RGBBase',['../classSupla_1_1Control_1_1RGBBase.html',1,'Supla::Control']]],
  ['rgbleds_12',['RGBLeds',['../classSupla_1_1Control_1_1RGBLeds.html',1,'Supla::Control']]],
  ['rgbwbase_13',['RGBWBase',['../classSupla_1_1Control_1_1RGBWBase.html',1,'Supla::Control']]],
  ['rgbwbuttonparameters_14',['RgbwButtonParameters',['../classRgbwButtonParameters.html',1,'RgbwButtonParameters'],['../classSupla_1_1Html_1_1RgbwButtonParameters.html',1,'Supla::Html::RgbwButtonParameters']]],
  ['rgbwleds_15',['RGBWLeds',['../classSupla_1_1Control_1_1RGBWLeds.html',1,'Supla::Control']]],
  ['rollershutter_16',['RollerShutter',['../classSupla_1_1Control_1_1RollerShutter.html',1,'Supla::Control::RollerShutter'],['../classSupla_1_1Control_1_1RollerShutter.html#acba5d1015d5783ba6c55068d6df5fa36',1,'Supla::Control::RollerShutter::RollerShutter(Supla::Io::Base *io, int pinUp, int pinDown, bool highIsOn=true, bool tiltFunctionsEnabled=false)'],['../classSupla_1_1Control_1_1RollerShutter.html#a53615c057896d3c56832c8e6fdc91496',1,'Supla::Control::RollerShutter::RollerShutter(int pinUp=-1, int pinDown=-1, bool highIsOn=true, bool tiltFunctionsEnabled=false)'],['../classSupla_1_1Control_1_1RollerShutter.html#addbc044855110145e22a5a2258670013',1,'Supla::Control::RollerShutter::RollerShutter(Supla::Io::IoPin pinUp, Supla::Io::IoPin pinDown, bool tiltFunctionsEnabled=false)']]],
  ['rollershutterconfig_17',['RollerShutterConfig',['../structSupla_1_1Control_1_1RollerShutterConfig.html',1,'Supla::Control']]],
  ['rollershutterinterface_18',['RollerShutterInterface',['../classRollerShutterInterface.html',1,'RollerShutterInterface'],['../classSupla_1_1Control_1_1RollerShutterInterface.html',1,'Supla::Control::RollerShutterInterface'],['../classSupla_1_1Control_1_1RollerShutterInterface.html#a5119c429201cf1df90b89cb52bb5e532',1,'Supla::Control::RollerShutterInterface::RollerShutterInterface()'],['../classRollerShutterInterface.html#a5119c429201cf1df90b89cb52bb5e532',1,'RollerShutterInterface::RollerShutterInterface()']]],
  ['rollershutterparameters_19',['RollerShutterParameters',['../classRollerShutterParameters.html',1,'RollerShutterParameters'],['../classSupla_1_1Html_1_1RollerShutterParameters.html',1,'Supla::Html::RollerShutterParameters']]],
  ['rollershutterstatedata_20',['RollerShutterStateData',['../structRollerShutterStateData.html',1,'']]],
  ['rollershutterwithtiltstatedata_21',['RollerShutterWithTiltStateData',['../structRollerShutterWithTiltStateData.html',1,'']]],
  ['rsaverificator_22',['RsaVerificator',['../classSupla_1_1RsaVerificator.html',1,'Supla']]],
  ['rsfbvalue_23',['RsFbValue',['../unionRsFbValue.html',1,'']]]
];
