var searchData=
[
  ['rain_0',['Rain',['../classSupla_1_1Sensor_1_1Rain.html',1,'Supla::Sensor']]],
  ['rangeinput_1',['rangeInput',['../classSupla_1_1WebSender.html#ad0f64949fc01b2329dd4864dc918bef3',1,'Supla::WebSender::rangeInput(const char *key, const NumericInputSpec &amp;spec, const char *cssClass=nullptr)'],['../classSupla_1_1WebSender.html#a0012c343a31272a77f948614f352b3de',1,'Supla::WebSender::rangeInput(const char *name, const char *id, const NumericInputSpec &amp;spec, const char *cssClass=nullptr)']]],
  ['registeredcmdactionmap_2',['RegisteredCmdActionMap',['../structSupla_1_1Html_1_1RegisteredCmdActionMap.html',1,'Supla::Html']]],
  ['registry_3',['Registry',['../classSupla_1_1Suplet_1_1Registry.html',1,'Supla::Suplet']]],
  ['relay_4',['Relay',['../classSupla_1_1Control_1_1Relay.html',1,'Supla::Control']]],
  ['relayflags_5',['RelayFlags',['../unionSupla_1_1Control_1_1Relay_1_1RelayFlags.html',1,'Supla::Control::Relay']]],
  ['relayhvacaggregator_6',['RelayHvacAggregator',['../classSupla_1_1Control_1_1RelayHvacAggregator.html',1,'Supla::Control']]],
  ['relayparameters_7',['RelayParameters',['../classSupla_1_1Html_1_1RelayParameters.html',1,'Supla::Html']]],
  ['relayrollershutterpair_8',['RelayRollerShutterPair',['../classSupla_1_1Control_1_1RelayRollerShutterPair.html',1,'Supla::Control']]],
  ['relayweeklyschedule_9',['RelayWeeklySchedule',['../classSupla_1_1Control_1_1RelayWeeklySchedule.html',1,'Supla::Control']]],
  ['remotedeviceconfig_10',['RemoteDeviceConfig',['../classSupla_1_1Device_1_1RemoteDeviceConfig.html',1,'Supla::Device']]],
  ['remoteoutputinterface_11',['RemoteOutputInterface',['../classSupla_1_1Control_1_1RemoteOutputInterface.html',1,'Supla::Control::RemoteOutputInterface'],['../classSupla_1_1Control_1_1RemoteOutputInterface.html#ae6dbfc3de7c7cf8a1d55e3ab78952155',1,'Supla::Control::RemoteOutputInterface::RemoteOutputInterface()']]],
  ['removesensor_12',['removeSensor',['../classSupla_1_1Control_1_1ValveBase.html#a1219856ed53ce43581a10a5853110fab',1,'Supla::Control::ValveBase']]],
  ['removesensordata_13',['removeSensorData',['../classSupla_1_1Sensor_1_1Container.html#ac97e08bfea047cd89d7af8ea2fe274fc',1,'Supla::Sensor::Container']]],
  ['requestedstate_14',['RequestedState',['../structSupla_1_1Control_1_1LightingPwmBase_1_1RequestedState.html',1,'Supla::Control::LightingPwmBase']]],
  ['responsewriter_15',['ResponseWriter',['../classSupla_1_1Debug_1_1ResponseWriter.html',1,'Supla::Debug']]],
  ['rgbbase_16',['RGBBase',['../classSupla_1_1Control_1_1RGBBase.html',1,'Supla::Control']]],
  ['rgbleds_17',['RGBLeds',['../classSupla_1_1Control_1_1RGBLeds.html',1,'Supla::Control']]],
  ['rgbwbase_18',['RGBWBase',['../classSupla_1_1Control_1_1RGBWBase.html',1,'Supla::Control']]],
  ['rgbwbuttonparameters_19',['RgbwButtonParameters',['../classSupla_1_1Html_1_1RgbwButtonParameters.html',1,'Supla::Html']]],
  ['rgbwleds_20',['RGBWLeds',['../classSupla_1_1Control_1_1RGBWLeds.html',1,'Supla::Control']]],
  ['rollershutter_21',['RollerShutter',['../classSupla_1_1Control_1_1RollerShutter.html',1,'Supla::Control::RollerShutter'],['../classSupla_1_1Control_1_1RollerShutter.html#acba5d1015d5783ba6c55068d6df5fa36',1,'Supla::Control::RollerShutter::RollerShutter(Supla::Io::Base *io, int pinUp, int pinDown, bool highIsOn=true, bool tiltFunctionsEnabled=false)'],['../classSupla_1_1Control_1_1RollerShutter.html#a53615c057896d3c56832c8e6fdc91496',1,'Supla::Control::RollerShutter::RollerShutter(int pinUp=-1, int pinDown=-1, bool highIsOn=true, bool tiltFunctionsEnabled=false)'],['../classSupla_1_1Control_1_1RollerShutter.html#addbc044855110145e22a5a2258670013',1,'Supla::Control::RollerShutter::RollerShutter(Supla::Io::IoPin pinUp, Supla::Io::IoPin pinDown, bool tiltFunctionsEnabled=false)']]],
  ['rollershutterconfig_22',['RollerShutterConfig',['../structSupla_1_1Control_1_1RollerShutterConfig.html',1,'Supla::Control']]],
  ['rollershutterinterface_23',['RollerShutterInterface',['../classSupla_1_1Control_1_1RollerShutterInterface.html',1,'Supla::Control::RollerShutterInterface'],['../classSupla_1_1Control_1_1RollerShutterInterface.html#a5119c429201cf1df90b89cb52bb5e532',1,'Supla::Control::RollerShutterInterface::RollerShutterInterface()']]],
  ['rollershutterparameters_24',['RollerShutterParameters',['../classSupla_1_1Html_1_1RollerShutterParameters.html',1,'Supla::Html']]],
  ['rollershutterstatedata_25',['RollerShutterStateData',['../structRollerShutterStateData.html',1,'']]],
  ['rollershutterwithtiltstatedata_26',['RollerShutterWithTiltStateData',['../structRollerShutterWithTiltStateData.html',1,'']]],
  ['rsaverificator_27',['RsaVerificator',['../classSupla_1_1RsaVerificator.html',1,'Supla']]],
  ['rsfbvalue_28',['RsFbValue',['../unionRsFbValue.html',1,'']]],
  ['runtime_29',['Runtime',['../classSupla_1_1Suplet_1_1Runtime.html',1,'Supla::Suplet']]],
  ['runtimeflags_30',['RuntimeFlags',['../structSupla_1_1Control_1_1ActionTrigger_1_1RuntimeFlags.html',1,'Supla::Control::ActionTrigger::RuntimeFlags'],['../structSupla_1_1Control_1_1Button_1_1RuntimeFlags.html',1,'Supla::Control::Button::RuntimeFlags'],['../structSupla_1_1Control_1_1Relay_1_1RuntimeFlags.html',1,'Supla::Control::Relay::RuntimeFlags']]],
  ['runtimehandler_31',['RuntimeHandler',['../classSupla_1_1Suplet_1_1RuntimeHandler.html',1,'Supla::Suplet']]]
];
