// SPDX-FileCopyrightText: AC SOFTWARE SP. Z O.O.
// SPDX-License-Identifier: GPL-2.0-or-later

#ifndef SRC_SUPLA_NETWORK_CONNECTION_ERROR_H_
#define SRC_SUPLA_NETWORK_CONNECTION_ERROR_H_

#include <stdint.h>

namespace Supla {

enum class ConnectionError : uint8_t {
  NONE,
  UNKNOWN,
  DNS,
  CONNECTION_TIMEOUT,
  CONNECTION_REFUSED,
  CONNECTION_LOST,
  SERVER_UNAVAILABLE,
  BAD_CREDENTIALS,
  NOT_AUTHORIZED,
  PROTOCOL_ERROR,
  TLS_ERROR,
  CERTIFICATE_ERROR,
  CERTIFICATE_EXPIRED,
  CERTIFICATE_NOT_YET_VALID,
  HOSTNAME_MISMATCH,
  UNTRUSTED_CERTIFICATE,
};

}  // namespace Supla

#endif  // SRC_SUPLA_NETWORK_CONNECTION_ERROR_H_
