physical_tests:
  disable_test:
    - if: IDF_TARGET != "esp32"
      reason: only manual test is performed for other targets
  disable:
    - if: CONFIG_NAME == "wifi" and SOC_WIFI_SUPPORTED != 1 and IDF_TARGET != "esp32"

unit_tests:
  disable_test:
    - if: IDF_TARGET != "esp32"
      reason: only manual test is performed for other targets

adapter_tests:
  disable_test:
    - if: IDF_TARGET != "esp32"
      reason: only manual test is performed for other targets