#!/usr/bin/env python3
"""Compile-time RAM object-size guard for the main SuplaDevice classes.

The check deliberately measures sizeof(T), not flash/code size.  Code size and
linker memory limits are target/application specific and should remain separate
from this class-layout guard.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path


PLATFORMS = ("host", "avr", "esp8266", "esp32")
DEFAULT_FQBN = {
    "avr": "arduino:avr:mega",
    "esp8266": "esp8266:esp8266:generic",
    "esp32": "esp32:esp32:esp32wrover",
}


def load_budgets(path: Path) -> list[dict]:
    with path.open(encoding="utf-8") as budgets_file:
        data = json.load(budgets_file)
    classes = data.get("classes")
    if not isinstance(classes, list) or not classes:
        raise ValueError("class budget file must contain a non-empty classes list")
    for item in classes:
        if not isinstance(item, dict) or not all(
            isinstance(item.get(key), str) for key in ("name", "header")
        ):
            raise ValueError("each class budget needs string name and header")
        limits = item.get("limits")
        if not isinstance(limits, dict):
            raise ValueError(f"{item['name']}: limits must be an object")
        for platform in PLATFORMS:
            if not isinstance(limits.get(platform), int) or limits[platform] <= 0:
                raise ValueError(f"{item['name']}: missing positive {platform} limit")
    return classes


def make_probe(classes: list[dict], platform: str) -> str:
    includes = "#include <SuplaDevice.h>\n#include <math.h>\n" + "\n".join(
        f"#include <{item['header']}>" for item in classes
    )
    checks = "\n".join(
        f'static_assert(sizeof({item["name"]}) <= {item["limits"][platform]}, '
        f'"class size budget exceeded: {item["name"]}");'
        for item in classes
    )
    return (
        "// Generated by extras/tools/check_class_sizes.py; do not edit.\n"
        f"{includes}\n\n{checks}\n\n"
        "void setup() {}\n"
        "void loop() {}\n"
    )


def make_measure_probe(classes: list[dict]) -> str:
    includes = "#include <SuplaDevice.h>\n#include <math.h>\n" + "\n".join(
        f"#include <{item['header']}>" for item in classes
    )
    checks = "\n".join(
        f'static_assert(sizeof({item["name"]}) <= 0, '
        f'"SUPLA_CLASS_SIZE:{index}");'
        for index, item in enumerate(classes)
    )
    return (
        "// Generated by extras/tools/check_class_sizes.py; do not edit.\n"
        f"{includes}\n\n{checks}\n\n"
        "void setup() {}\n"
        "void loop() {}\n"
    )


def make_symbol_measure_probe(classes: list[dict]) -> str:
    includes = (
        "#include <SuplaDevice.h>\n"
        "#include <math.h>\n"
        "#if defined(__AVR__)\n"
        "#include <avr/pgmspace.h>\n"
        "#endif\n"
        + "\n".join(
            f"#include <{item['header']}>" for item in classes
        )
    )
    arrays = "\n".join(
        f'const volatile uint8_t supla_class_size_{index}[sizeof({item["name"]})] '
        "PROGMEM __attribute__((used)) = {};"
        for index, item in enumerate(classes)
    )
    references = "\n".join(
        f"  result ^= supla_class_size_{index}[0];"
        for index in range(len(classes))
    )
    return (
        "// Generated by extras/tools/check_class_sizes.py; do not edit.\n"
        f"{includes}\n\nextern \"C\" {{\n{arrays}\n}}\n\n"
        "volatile uint8_t supla_class_size_sink = 0;\n"
        "void setup() {\n"
        "  uint8_t result = 0;\n"
        f"{references}\n"
        "  supla_class_size_sink = result;\n"
        "}\n"
        "void loop() {}\n"
    )


def run(command: list[str], cwd: Path | None = None) -> int:
    print("+", " ".join(command))
    environment = os.environ.copy()
    # The repository's host builds may use a read-only ccache mount.
    environment["CCACHE_DISABLE"] = "1"
    completed = subprocess.run(command, cwd=cwd, env=environment)
    return completed.returncode


def run_output(command: list[str], cwd: Path | None = None) -> tuple[int, str]:
    print("+", " ".join(command))
    environment = os.environ.copy()
    environment["CCACHE_DISABLE"] = "1"
    completed = subprocess.run(
        command,
        cwd=cwd,
        env=environment,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
    )
    print(completed.stdout, end="")
    return completed.returncode, completed.stdout


def parse_measurements(output: str, classes: list[dict]) -> list[int]:
    measurements: dict[int, int] = {}
    pending_index = None
    for line in output.splitlines():
        failed = re.search(r"static assertion failed: SUPLA_CLASS_SIZE:(\d+)", line)
        if failed:
            pending_index = int(failed.group(1))
            continue
        reduced = re.search(r"comparison reduces to.*\((\d+) <= 0\)", line)
        if reduced and pending_index is not None:
            measurements[pending_index] = int(reduced.group(1))
            pending_index = None

    missing = [
        index for index in range(len(classes)) if index not in measurements
    ]
    if missing:
        names = ", ".join(classes[index]["name"] for index in missing)
        raise RuntimeError(f"could not measure class size for: {names}")
    return [measurements[index] for index in range(len(classes))]


def parse_elf_measurements(build_path: Path, classes: list[dict]) -> list[int]:
    elf_files = sorted(build_path.rglob("*.elf"))
    if len(elf_files) != 1:
        raise RuntimeError(
            f"expected one ELF below {build_path}, found {len(elf_files)}"
        )
    nm = shutil.which("nm")
    if nm is None:
        raise RuntimeError("nm not found")
    completed = subprocess.run(
        [nm, "-S", "--format=posix", str(elf_files[0])],
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        check=True,
    )
    measurements: dict[int, int] = {}
    names = {
        f"supla_class_size_{index}": index for index in range(len(classes))
    }
    for line in completed.stdout.splitlines():
        fields = line.split()
        if len(fields) < 4:
            continue
        name = fields[0].lstrip("_")
        if name in names:
            measurements[names[name]] = int(fields[3], 16)
    missing = [
        index for index in range(len(classes)) if index not in measurements
    ]
    if missing:
        names = ", ".join(classes[index]["name"] for index in missing)
        raise RuntimeError(f"could not read class size from ELF for: {names}")
    return [measurements[index] for index in range(len(classes))]


def check_host(repo_root: Path, classes: list[dict], temp_root: Path) -> int:
    probe = temp_root / "class_size_probe.cpp"
    probe.write_text(
        "#define SUPLA_TEST 1\n"
        + make_probe(classes, "host").replace(
            "void setup() {}\nvoid loop() {}", "int main() { return 0; }"
        ),
        encoding="utf-8",
    )
    compiler = shutil.which("g++")
    if compiler is None:
        print("class-size: g++ not found", file=sys.stderr)
        return 1
    return run(
        [
            compiler,
            "-std=c++17",
            "-fsyntax-only",
            "-DSUPLA_DEVICE",
            "-Isrc",
            "-Isrc/supla-common",
            str(probe),
        ],
        cwd=repo_root,
    )


def check_arduino(
    repo_root: Path,
    classes: list[dict],
    platform: str,
    fqbn: str,
    arduino_cli: str,
    temp_root: Path,
) -> int:
    sketch = temp_root / platform
    sketch.mkdir()
    (sketch / f"{platform}.ino").write_text(
        make_probe(classes, platform), encoding="utf-8"
    )
    build_path = temp_root / f"build-{platform}"
    return run(
        [
            arduino_cli,
            "compile",
            "--fqbn",
            fqbn,
            "--build-path",
            str(build_path),
            "--library",
            str(repo_root),
            str(sketch),
        ],
        cwd=repo_root,
    )


def measure_host(repo_root: Path, classes: list[dict], temp_root: Path) -> list[int]:
    probe = temp_root / "class_size_measure.cpp"
    probe.write_text(
        "#define SUPLA_TEST 1\n" + make_measure_probe(classes), encoding="utf-8"
    )
    compiler = shutil.which("g++")
    if compiler is None:
        raise RuntimeError("g++ not found")
    result, output = run_output(
        [
            compiler,
            "-std=c++17",
            "-fsyntax-only",
            "-DSUPLA_DEVICE",
            "-Isrc",
            "-Isrc/supla-common",
            str(probe),
        ],
        cwd=repo_root,
    )
    if result == 0:
        raise RuntimeError("measurement probe unexpectedly compiled successfully")
    return parse_measurements(output, classes)


def measure_arduino(
    repo_root: Path,
    classes: list[dict],
    platform: str,
    fqbn: str,
    arduino_cli: str,
    temp_root: Path,
) -> list[int]:
    sketch = temp_root / f"measure-{platform}"
    sketch.mkdir()
    (sketch / f"measure-{platform}.ino").write_text(
        make_symbol_measure_probe(classes), encoding="utf-8"
    )
    build_path = temp_root / f"measure-build-{platform}"
    result = run(
        [
            arduino_cli,
            "compile",
            "--fqbn",
            fqbn,
            "--build-path",
            str(build_path),
            "--library",
            str(repo_root),
            str(sketch),
        ],
        cwd=repo_root,
    )
    if result:
        raise RuntimeError("measurement probe failed to compile")
    return parse_elf_measurements(build_path, classes)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--platform",
        action="append",
        choices=PLATFORMS,
        help="platform to check; may be repeated (default: host)",
    )
    parser.add_argument(
        "--fqbn",
        action="append",
        metavar="PLATFORM=FQBN",
        help="override an Arduino FQBN, e.g. esp32=esp32:esp32:esp32wrover",
    )
    parser.add_argument(
        "--arduino-cli", default="arduino-cli", help="arduino-cli executable"
    )
    parser.add_argument(
        "--measure",
        action="store_true",
        help="report actual sizeof values instead of checking budgets",
    )
    parser.add_argument(
        "--budgets",
        type=Path,
        help="budget JSON (default: class_size_budgets.json next to this script)",
    )
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parents[2]
    budgets_path = args.budgets or Path(__file__).with_name("class_size_budgets.json")
    classes = load_budgets(budgets_path)
    platforms = args.platform or ["host"]
    fqbn = dict(DEFAULT_FQBN)
    for value in args.fqbn or []:
        try:
            platform, value = value.split("=", 1)
        except ValueError as error:
            raise SystemExit(f"invalid --fqbn value: {value!r}") from error
        if platform not in DEFAULT_FQBN:
            raise SystemExit(f"--fqbn platform must be one of: {', '.join(DEFAULT_FQBN)}")
        fqbn[platform] = value

    temporary_root = Path("/tmp/codex")
    temporary_root.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(
        prefix="supla-class-size-", dir=temporary_root
    ) as directory:
        temp_root = Path(directory)
        for platform in platforms:
            if args.measure and platform == "host":
                sizes = measure_host(repo_root, classes, temp_root)
                for item, size in zip(classes, sizes):
                    print(f"{platform}: {item['name']}={size}")
                continue
            if args.measure:
                sizes = measure_arduino(
                    repo_root,
                    classes,
                    platform,
                    fqbn[platform],
                    args.arduino_cli,
                    temp_root,
                )
                for item, size in zip(classes, sizes):
                    print(f"{platform}: {item['name']}={size}")
                continue
            if platform == "host":
                result = check_host(repo_root, classes, temp_root)
            else:
                result = check_arduino(
                    repo_root,
                    classes,
                    platform,
                    fqbn[platform],
                    args.arduino_cli,
                    temp_root,
                )
            if result:
                print(f"class-size: {platform} check failed", file=sys.stderr)
                return result
            print(f"class-size: {platform} check passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
