#!/usr/bin/env python3
"""Generate the CSS string embedded in the firmware HTML generator."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "extras/resources/css_for_cfg_page.css"
OUTPUT = ROOT / "src/supla/network/html_generator_styles.inc"


def minify_css(css: str) -> str:
    result = []
    quote = None
    escaped = False
    pending_space = False
    i = 0

    while i < len(css):
        char = css[i]

        if quote is not None:
            result.append(char)
            if escaped:
                escaped = False
            elif char == "\\":
                escaped = True
            elif char == quote:
                quote = None
            i += 1
            continue

        if css.startswith("/*", i):
            end = css.find("*/", i + 2)
            if end == -1:
                raise ValueError("unterminated CSS comment")
            i = end + 2
            continue

        if char in "\"'":
            if pending_space and result and result[-1] not in "{}[(:,;>+~":
                result.append(" ")
            result.append(char)
            quote = char
            pending_space = False
            i += 1
            continue

        if char.isspace():
            pending_space = True
            i += 1
            continue

        if char in "{}:;,>+~":
            if result and result[-1] == " ":
                result.pop()
            result.append(char)
            pending_space = False
            i += 1
            continue

        if pending_space and result and result[-1] not in "{}[(:,;>+~":
            result.append(" ")
        result.append(char)
        pending_space = False
        i += 1

    while result and result[-1] == " ":
        result.pop()

    minified = "".join(result)
    return minified.replace(";}", "}")


def cpp_escape(text: str) -> list[str]:
    tokens = []
    for byte in text.encode("utf-8"):
        if 32 <= byte <= 126 and byte not in (ord('"'), ord("\\")):
            tokens.append(chr(byte))
        elif byte == ord('"'):
            tokens.append('\\"')
        elif byte == ord("\\"):
            tokens.append("\\\\")
        else:
            tokens.append(f"\\{byte:03o}")
    return tokens


def make_output(css: str) -> str:
    tokens = cpp_escape(f"<style>{minify_css(css)}</style>")
    lines = [
        "// Generated from extras/resources/css_for_cfg_page.css.",
        "// Do not edit this file manually; run generate_html_generator_styles.py.",
        "const char styles[] =",
    ]

    current = []
    current_length = 0
    for token in tokens:
        if current and current_length + len(token) > 76:
            lines.append('    "' + "".join(current) + '"')
            current = []
            current_length = 0
        current.append(token)
        current_length += len(token)

    if current:
        lines.append('    "' + "".join(current) + '"')

    lines[-1] += ";"
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="check that the generated file is up to date",
    )
    args = parser.parse_args()

    generated = make_output(SOURCE.read_text(encoding="utf-8"))

    if args.check:
        try:
            current = OUTPUT.read_text(encoding="utf-8")
        except FileNotFoundError:
            print(f"missing generated file: {OUTPUT}", file=sys.stderr)
            return 1
        if current != generated:
            print(
                f"generated file is out of date: {OUTPUT}\n"
                "run extras/tools/generate_html_generator_styles.py",
                file=sys.stderr,
            )
            return 1
        return 0

    OUTPUT.write_text(generated, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
