/*
   Copyright (C) AC SOFTWARE SP. Z O.O

   This program is free software; you can redistribute it and/or
   modify it under the terms of the GNU General Public License
   as published by the Free Software Foundation; either version 2
   of the License, or (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
*/

#ifndef SRC_SUPLA_CHANNEL_FUNCTION_STRING_H_
#define SRC_SUPLA_CHANNEL_FUNCTION_STRING_H_

#include <supla-common/proto.h>

namespace Supla {

inline const char *channelFunctionToString(int function) {
  switch (function) {
    case SUPLA_CHANNELFNC_NONE:
      return "NONE";
    case SUPLA_CHANNELFNC_CONTROLLINGTHEGATEWAYLOCK:
      return "GATEWAY_LOCK";
    case SUPLA_CHANNELFNC_CONTROLLINGTHEGATE:
      return "GATE";
    case SUPLA_CHANNELFNC_CONTROLLINGTHEGARAGEDOOR:
      return "GARAGE_DOOR";
    case SUPLA_CHANNELFNC_THERMOMETER:
      return "THERMOMETER";
    case SUPLA_CHANNELFNC_HUMIDITY:
      return "HUMIDITY";
    case SUPLA_CHANNELFNC_HUMIDITYANDTEMPERATURE:
      return "HUMIDITY_TEMPERATURE";
    case SUPLA_CHANNELFNC_OPENINGSENSOR_GATEWAY:
      return "OPENING_SENSOR_GATEWAY";
    case SUPLA_CHANNELFNC_OPENINGSENSOR_GATE:
      return "OPENING_SENSOR_GATE";
    case SUPLA_CHANNELFNC_OPENINGSENSOR_GARAGEDOOR:
      return "OPENING_SENSOR_GARAGE_DOOR";
    case SUPLA_CHANNELFNC_NOLIQUIDSENSOR:
      return "NO_LIQUID_SENSOR";
    case SUPLA_CHANNELFNC_CONTROLLINGTHEDOORLOCK:
      return "DOOR_LOCK";
    case SUPLA_CHANNELFNC_OPENINGSENSOR_DOOR:
      return "OPENING_SENSOR_DOOR";
    case SUPLA_CHANNELFNC_CONTROLLINGTHEROLLERSHUTTER:
      return "ROLLER_SHUTTER";
    case SUPLA_CHANNELFNC_CONTROLLINGTHEROOFWINDOW:
      return "ROOF_WINDOW";
    case SUPLA_CHANNELFNC_OPENINGSENSOR_ROLLERSHUTTER:
      return "OPENING_SENSOR_ROLLER_SHUTTER";
    case SUPLA_CHANNELFNC_OPENINGSENSOR_ROOFWINDOW:
      return "OPENING_SENSOR_ROOF_WINDOW";
    case SUPLA_CHANNELFNC_POWERSWITCH:
      return "POWER_SWITCH";
    case SUPLA_CHANNELFNC_LIGHTSWITCH:
      return "LIGHT_SWITCH";
    case SUPLA_CHANNELFNC_RING:
      return "RING";
    case SUPLA_CHANNELFNC_ALARM:
      return "ALARM";
    case SUPLA_CHANNELFNC_NOTIFICATION:
      return "NOTIFICATION";
    case SUPLA_CHANNELFNC_DIMMER:
      return "DIMMER";
    case SUPLA_CHANNELFNC_DIMMER_CCT:
      return "DIMMER_CCT";
    case SUPLA_CHANNELFNC_RGBLIGHTING:
      return "RGB_LIGHTING";
    case SUPLA_CHANNELFNC_DIMMERANDRGBLIGHTING:
      return "DIMMER_RGB_LIGHTING";
    case SUPLA_CHANNELFNC_DIMMER_CCT_AND_RGB:
      return "DIMMER_CCT_RGB";
    case SUPLA_CHANNELFNC_DEPTHSENSOR:
      return "DEPTH_SENSOR";
    case SUPLA_CHANNELFNC_DISTANCESENSOR:
      return "DISTANCE_SENSOR";
    case SUPLA_CHANNELFNC_OPENINGSENSOR_WINDOW:
      return "OPENING_SENSOR_WINDOW";
    case SUPLA_CHANNELFNC_HOTELCARDSENSOR:
      return "HOTEL_CARD_SENSOR";
    case SUPLA_CHANNELFNC_ALARMARMAMENTSENSOR:
      return "ALARM_ARMAMENT_SENSOR";
    case SUPLA_CHANNELFNC_MAILSENSOR:
      return "MAIL_SENSOR";
    case SUPLA_CHANNELFNC_WINDSENSOR:
      return "WIND_SENSOR";
    case SUPLA_CHANNELFNC_PRESSURESENSOR:
      return "PRESSURE_SENSOR";
    case SUPLA_CHANNELFNC_RAINSENSOR:
      return "RAIN_SENSOR";
    case SUPLA_CHANNELFNC_WEIGHTSENSOR:
      return "WEIGHT_SENSOR";
    case SUPLA_CHANNELFNC_WEATHER_STATION:
      return "WEATHER_STATION";
    case SUPLA_CHANNELFNC_STAIRCASETIMER:
      return "STAIRCASE_TIMER";
    case SUPLA_CHANNELFNC_ELECTRICITY_METER:
      return "ELECTRICITY_METER";
    case SUPLA_CHANNELFNC_IC_ELECTRICITY_METER:
      return "IC_ELECTRICITY_METER";
    case SUPLA_CHANNELFNC_IC_GAS_METER:
      return "IC_GAS_METER";
    case SUPLA_CHANNELFNC_IC_WATER_METER:
      return "IC_WATER_METER";
    case SUPLA_CHANNELFNC_IC_HEAT_METER:
      return "IC_HEAT_METER";
    case SUPLA_CHANNELFNC_IC_EVENTS:
      return "IC_EVENTS";
    case SUPLA_CHANNELFNC_IC_SECONDS:
      return "IC_SECONDS";
    case SUPLA_CHANNELFNC_THERMOSTAT_HEATPOL_HOMEPLUS:
      return "THERMOSTAT_HEATPOL_HOMEPLUS";
    case SUPLA_CHANNELFNC_HVAC_THERMOSTAT:
      return "HVAC_THERMOSTAT";
    case SUPLA_CHANNELFNC_HVAC_THERMOSTAT_HEAT_COOL:
      return "HVAC_THERMOSTAT_HEAT_COOL";
    case SUPLA_CHANNELFNC_HVAC_DRYER:
      return "HVAC_DRYER";
    case SUPLA_CHANNELFNC_HVAC_FAN:
      return "HVAC_FAN";
    case SUPLA_CHANNELFNC_HVAC_THERMOSTAT_DIFFERENTIAL:
      return "HVAC_THERMOSTAT_DIFFERENTIAL";
    case SUPLA_CHANNELFNC_HVAC_DOMESTIC_HOT_WATER:
      return "HVAC_DOMESTIC_HOT_WATER";
    case SUPLA_CHANNELFNC_VALVE_OPENCLOSE:
      return "VALVE_OPENCLOSE";
    case SUPLA_CHANNELFNC_VALVE_PERCENTAGE:
      return "VALVE_PERCENTAGE";
    case SUPLA_CHANNELFNC_GENERAL_PURPOSE_MEASUREMENT:
      return "GENERAL_PURPOSE_MEASUREMENT";
    case SUPLA_CHANNELFNC_GENERAL_PURPOSE_METER:
      return "GENERAL_PURPOSE_METER";
    case SUPLA_CHANNELFNC_CONTROLLINGTHEENGINESPEED:
      return "ENGINE_SPEED";
    case SUPLA_CHANNELFNC_ACTIONTRIGGER:
      return "ACTION_TRIGGER";
    case SUPLA_CHANNELFNC_DIGIGLASS_HORIZONTAL:
      return "DIGIGLASS_HORIZONTAL";
    case SUPLA_CHANNELFNC_DIGIGLASS_VERTICAL:
      return "DIGIGLASS_VERTICAL";
    case SUPLA_CHANNELFNC_CONTROLLINGTHEFACADEBLIND:
      return "FACADE_BLIND";
    case SUPLA_CHANNELFNC_TERRACE_AWNING:
      return "TERRACE_AWNING";
    case SUPLA_CHANNELFNC_PROJECTOR_SCREEN:
      return "PROJECTOR_SCREEN";
    case SUPLA_CHANNELFNC_CURTAIN:
      return "CURTAIN";
    case SUPLA_CHANNELFNC_VERTICAL_BLIND:
      return "VERTICAL_BLIND";
    case SUPLA_CHANNELFNC_ROLLER_GARAGE_DOOR:
      return "ROLLER_GARAGE_DOOR";
    case SUPLA_CHANNELFNC_PUMPSWITCH:
      return "PUMP_SWITCH";
    case SUPLA_CHANNELFNC_HEATORCOLDSOURCESWITCH:
      return "HEAT_OR_COLD_SOURCE_SWITCH";
    case SUPLA_CHANNELFNC_CONTAINER:
      return "CONTAINER";
    case SUPLA_CHANNELFNC_SEPTIC_TANK:
      return "SEPTIC_TANK";
    case SUPLA_CHANNELFNC_WATER_TANK:
      return "WATER_TANK";
    case SUPLA_CHANNELFNC_CONTAINER_LEVEL_SENSOR:
      return "CONTAINER_LEVEL_SENSOR";
    case SUPLA_CHANNELFNC_FLOOD_SENSOR:
      return "FLOOD_SENSOR";
    case SUPLA_CHANNELFNC_MOTION_SENSOR:
      return "MOTION_SENSOR";
    case SUPLA_CHANNELFNC_BINARY_SENSOR:
      return "BINARY_SENSOR";
    default:
      return "UNKNOWN";
  }
}

}  // namespace Supla

#endif  // SRC_SUPLA_CHANNEL_FUNCTION_STRING_H_
