// SPDX-FileCopyrightText: AC SOFTWARE SP. Z O.O.
// SPDX-License-Identifier: GPL-2.0-or-later

#ifndef EXTRAS_TEST_DOUBLES_ESP_IDF_MBEDTLS_X509_H_
#define EXTRAS_TEST_DOUBLES_ESP_IDF_MBEDTLS_X509_H_

#define MBEDTLS_ERR_X509_CERT_VERIFY_FAILED -0x2700

#endif  // EXTRAS_TEST_DOUBLES_ESP_IDF_MBEDTLS_X509_H_
