// SPDX-License-Identifier: GPL-2.0-or-later
// Copyright 2026 AC SOFTWARE SP. Z O.O.

#ifndef EXTRAS_TEST_SUPLANESPUDPTESTS_FAKES_LWIP_IP4_ADDR_H_
#define EXTRAS_TEST_SUPLANESPUDPTESTS_FAKES_LWIP_IP4_ADDR_H_

#include <stdint.h>

#endif  // EXTRAS_TEST_SUPLANESPUDPTESTS_FAKES_LWIP_IP4_ADDR_H_
